server {
    listen 80;
    server_name skinlabpro.uz www.skinlabpro.uz;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect to HTTPS (once certs are ready)
    location / {
        # return 301 https://$host$request_uri;
        root /usr/share/nginx/html;
    }
}
